Updates to Java Starter Project
BattlesnakeOfficial/starter-snake-java pull request #18
Opened 2021-10-06 13:50 UTC by Nettogrof

As suggested in the [feedback discussion](https://github.com/BattlesnakeOfficial/feedback/discussions/114), 

1. I added a  "avoid neck function" to avoid to collide with its neck.
2.  Added and update comments to be similar to comments in others starter-snake project.
3.  Added tests for the "avec neck function" 

I also update the ReadMe file, to be more similar to other project readme, and remove any "Slack" reference.

2021-10-06 15:07 UTC, bvanvugt commented
Thanks @Nettogrof! We'll take a look this week, as I am not qualified :)

2021-10-07 18:34 UTC, aurorawalker requested changes
Thank you for your thoroughness! Great PR. I've done a visual review, spotted some minor typos. Going to publish those comments now, but next step for me will be running the complete PR and taking it for a spin. :D

2021-10-07 18:34 UTC, aurorawalker commented on README.md
> +4. Once your Repl is ready to run, click `Run â–¶ï¸�` at the top of the screen. You should see maven (and any other dependencies) being installed. Once installation is complete, your Battlesnake serv
Whoop - looks like the IDE or similar did something odd with the 'Run >' part of this.

2021-10-07 18:34 UTC, aurorawalker commented on src/main/java/com/battlesnake/starter/Snake.java
> +		 * @param moveRequest JsonNoe of all Game Board data as received from the
Small typo - JsonNoe  - > JsonNode

2021-10-07 18:34 UTC, aurorawalker commented on src/main/java/com/battlesnake/starter/Snake.java
> +			// TODO: Using information from 'data', don't let your Battlesnake pick a move
I think the comment here (and one below on line 179) is a bit too literally copied from the Python starter project comments. I think instead of saying " Using information from 'data'..." it would be better to say "Using information from 'moveRequest'..." as that is the name of the object in this Java starter project.

2021-10-07 19:43 UTC, Nettogrof commented on src/main/java/com/battlesnake/starter/Snake.java
> +			// TODO: Using information from 'data', don't let your Battlesnake pick a move
I plead guilty of  "copy-pasta" ;)

2021-10-07 20:33 UTC, aurorawalker commented on src/main/java/com/battlesnake/starter/Snake.java
> +			// TODO: Using information from 'data', don't let your Battlesnake pick a move
Literally happens to all of us. That's why I love code review so much - means I've got a buddy checking my work for when I inevitably copy-pasta wrong. :D Code reviewers make up for most standard human errors.

2021-10-07 21:04 UTC, Nettogrof commented
All should be fixed now

2021-10-07 23:55 UTC, aurorawalker commented
@Nettogrof 
Functionally looks good! Successfully was able to create and run a Replit, as well as run the unit test suite. Great job, and thank you for this!

Sorry to be a nitpicking-Nancy, but I think there is one last thing I'd like to follow up on. The pull request shows an edit to more lines that there should be, so I pulled the repo down and see that the files you modified also had the line ending changed to CR/LF (carriage return and line feed) while the rest of the repository is just LF (line feed).
CR/LF is what you see on Windows, where LF is what you'll see on unix systems.

The other files in the repo have LF line endings, and I'd like to stay consistent on that and keep all files as LF. If you use Visual Studio Code as your editor, there is a handy toggle button between LF and CR/LF in the bottom-right-hand corner.
<img width="332" alt="vscode_lf" src="https://user-images.githubusercontent.com/663009/136477413-7cd09115-2717-4dd5-a7a8-38e4b7075896.png">

2021-10-08 17:16 UTC, aurorawalker approved these changes
You are a champ! Thanks for addressing the nitpicks. Great work.

2021-10-08 17:17 UTC, merged